### ISSUE TITLE
No HEAD requests are supported

### ISSUE THREAD

**Issue by aylen384** [Sqozz/schort#3]
I tried to send a head request to get the target URL:

```
curl -vI http://s.qa.suse.de/raPS
*   Trying 10.162.0.23...
* TCP_NODELAY set
* Connected to s.qa.suse.de (10.162.0.23) port 80 (#0)
> HEAD /raPS HTTP/1.1
> Host: s.qa.suse.de
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 500 INTERNAL SERVER ERROR
```

**Comment by sqozz** [comment]
Indeed, schort does not _yet_ support HEAD requests. However, I really like the idea of using HEAD requests to resolve links and will try to add it into schort.

As a workaround you could use a normal GET request combined with the "resolve" parameter (value of that parameter doesn't matter) - this is also explained in the [API description](https://github.com/sqozz/schort/blob/master/templates/index.html#L32). E.g. in your case, just use the following curl statement:

```
curl http://s.qa.suse.de/raPS?resolve
```

**Comment by sqozz** [comment]
Thanks to https://github.com/sqozz/schort/pull/4 we can now close this :)
